project:
  type: book
  output-dir: _book

book:
  title: "Git for Scientists"
  author: "Lars Schöbitz"
  reader-mode: true
  site-url: https://gitforsci.github.io/website/
  repo-url: https://github.com/gitforsci/website/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - intro.qmd
    - part: part-pedagogy.qmd
      chapters:
        - ch-philosophy.qmd
        - ch-course-shape.qmd
        - ch-live-drawings.qmd
    - part: part-prerequisites.qmd
      chapters:
        - ch-teacher-setup.qmd
        - ch-learner-setup.qmd
    - part: part-setup.qmd
      chapters:
        - ch-three-orgs.qmd
        - ch-create-orgs.qmd
        - ch-website.qmd
    - part: part-delivery.qmd
      chapters:
        - ch-before.qmd
        - ch-run-of-show.qmd
    - part: part-reuse.qmd
      chapters:
        - ch-new-iteration.qmd
        - ch-citation-license.qmd
    - summary.qmd

  appendices:
    - appendix-checklists.qmd
    - appendix-drawings.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]

execute:
  freeze: auto
